using Pkg
Pkg.activate(".")

using Distributions
using TimerOutputs
using PauliStrings
const ps = PauliStrings
using Random
using JLD2
using Dates
using JSON

"""
PAULI PROPAGATION FOR U(1) CIRCUIT CORRELATION FUNCTIONS

This project studies correlation functions of U(1) symmetric quantum circuits using 
Pauli propagation methods. The key insights are:

1. U(1) SYMMETRY: Circuits preserve total magnetization Σᵢ Zᵢ, relevant for models
   like the Heisenberg model or systems with particle number conservation.

2. PAULI PROPAGATION: Instead of evolving the full quantum state |ψ(t)⟩, we evolve
   Pauli operators O(t) = U†(t) O U(t) using the identity:
   exp(iθP) O exp(-iθP) = cos(θ)O + i sin(θ)[P,O]
   This allows efficient computation of correlation functions ⟨Z_i(t)⟩.

3. CORRELATION FUNCTIONS: We compute ⟨Z_i(t)⟩ = Tr[O(t) Z_i]/2^N where O(0) = Z_j
   for some initial site j. This measures how local magnetization spreads.

4. TRUNCATION: The number of Pauli terms grows exponentially, so we truncate to
   the M largest terms while preserving important operators (local Z's).

5. WEIGHT DISTRIBUTION: We track how operator "weight" (number of non-identity
   Paulis) evolves, characterizing operator spreading and entanglement growth.
"""

### Gate application functions ###

"""
    apply_gate(O, P, θ; M=2^10, keep=Operator(0))

Apply a single quantum gate to a Pauli operator using the Pauli propagation method.

This function implements the core of Pauli propagation: given a Pauli operator O and 
a gate generated by Pauli generator P with angle θ, it computes the evolved operator
O' = exp(iθP) O exp(-iθP) using the formula:

O' = cos(θ)O + i*sin(θ)*[P,O]  (if [P,O] anticommutes with P)
O' = O                          (if [P,O] commutes with P)

# Arguments
- `O`: Input Pauli operator to evolve
- `P`: Pauli generator of the gate (single Pauli string)
- `θ`: Gate angle parameter
- `M`: Maximum number of Pauli terms to keep (truncation parameter)
- `keep`: Specific operators to always preserve during truncation

# Returns
- Evolved Pauli operator after applying the gate
"""
function apply_gate(O, P, θ; M=2^10, keep=Operator(0))
    @assert length(P.strings) == 1 "Gate must be generated by a single pauli generator"
    d = ps.emptydict(O)
    P = P.strings[1]
    for i in 1:length(O.strings)
        O_i, c_i = O.strings[i], O.coeffs[i]
        anticom = ps.anticommutator(O_i, P)

        if anticom[2] == 0
            c = c_i * cos(θ)
            ps.setwith!(+, d, O_i, c)
            p_n, k_n = ps.prod(P, O_i)

            c_n = sin(θ) * c_i * k_n * im
            ps.setwith!(+, d, p_n, c_n)
        
        else
            ps.setwith!(+, d, O_i, c_i)
        end

    end
    O_new = Operator(collect(keys(d)), collect(values(d)))
    O_new = ps.trim(O_new, M; keep=keep, keepnorm=false)
    return O_new
end

"""
    apply_gate_list(O, gate_list, angle_list; M=2^10, noise=0, keep=Operator(0))

Apply a sequence of quantum gates to a Pauli operator.

This function sequentially applies multiple gates to evolve the Pauli operator
through a quantum circuit. After all gates are applied, optional noise can be added.

# Arguments
- `O`: Initial Pauli operator
- `gate_list`: List of Pauli generators for each gate
- `angle_list`: List of angles corresponding to each gate
- `M`: Truncation parameter for maximum Pauli terms
- `noise`: Noise level to add after evolution
- `keep`: Operators to preserve during truncation

# Returns
- Final evolved Pauli operator after the full circuit
"""
function apply_gate_list(O, gate_list, angle_list; M=2^10, noise=0, keep=Operator(0))
    for i in 1:length(gate_list)
        O = apply_gate(O, gate_list[i], angle_list[i], M=M, keep=keep)
    end
    O = ps.add_noise(O, noise)
    return O
end

### Construction ###

"""
    single_Z_operators(N)

Generate all single-qubit Z operators for an N-qubit system.

Creates a list of N Pauli operators, each being a Z gate acting on a single qubit.
These are used as observables to compute correlation functions ⟨Z_i(t)⟩.

# Arguments
- `N`: Number of qubits in the system

# Returns
- Array of N Pauli operators, where ops[i] = Z_i
"""
function single_Z_operators(N)
    ops = Operator[]
    for i in 1:N
        O = Operator(N)
        O += "Z", i
        push!(ops, O)
    end
    return ops
end

"""
    random_circuit(N, trial)

Construct a random U(1) symmetric quantum circuit.

Generates a brick-layer circuit with random angles, implementing U(1) symmetric gates.
The circuit consists of:
1. Single-qubit Z rotations (θ1, θ2, θ3, θ4)
2. Two-qubit interactions: XX, YY, ZZ with strengths Jx, Jz

The circuit maintains U(1) symmetry by only using gates that preserve total magnetization.

# Arguments
- `N`: Number of qubits
- `trial`: Trial number (selects which random angles to use)

# Returns
- `gate_list`: List of Pauli generators for each gate
- `angle_list`: Corresponding angles for each gate
"""
function random_circuit(N, trial)
    angles = load_angles(N)[trial]
    gate_list = []
    angle_list = []

    for j in 1:2:N
        angles_bond = angles[j]
        θ1, θ2, Jx, Jz, θ3, θ4 = angles_bond["θ1"], angles_bond["θ2"], angles_bond["Jx"], angles_bond["Jz"], angles_bond["θ3"], angles_bond["θ4"]

        rot_1 = ps.Operator(N)
        rot_1 += "Z", j
        push!(gate_list, rot_1)
        push!(angle_list, θ1)

        rot_2 = ps.Operator(N)
        rot_2 += "Z", j+1
        push!(gate_list, rot_2)
        push!(angle_list, θ2)

        rot_xx = ps.Operator(N)
        rot_xx += "X", j, "X", j+1
        push!(gate_list, rot_xx)
        push!(angle_list, Jx)

        rot_yy = ps.Operator(N)
        rot_yy += "Y", j, "Y", j+1
        push!(gate_list, rot_yy)
        push!(angle_list, Jx)

        rot_zz = ps.Operator(N)
        rot_zz += "Z", j, "Z", j+1
        push!(gate_list, rot_zz)
        push!(angle_list, Jz)

        rot_3 = ps.Operator(N)
        rot_3 += "Z", j
        push!(gate_list, rot_3)
        push!(angle_list, θ3)

        rot_4 = ps.Operator(N)
        rot_4 += "Z", j+1
        push!(gate_list, rot_4)
        push!(angle_list, θ4)
    end

    for j in 2:2:N
        angles_bond = angles[j]
        θ1, θ2, Jx, Jz, θ3, θ4 = angles_bond["θ1"], angles_bond["θ2"], angles_bond["Jx"], angles_bond["Jz"], angles_bond["θ3"], angles_bond["θ4"]

        rot_1 = ps.Operator(N)
        rot_1 += "Z", j
        push!(gate_list, rot_1)
        push!(angle_list, θ1)

        rot_2 = ps.Operator(N)
        rot_2 += "Z", j%N+1
        push!(gate_list, rot_2)
        push!(angle_list, θ2)

        rot_xx = ps.Operator(N)
        rot_xx += "X", j, "X", j%N+1
        push!(gate_list, rot_xx)
        push!(angle_list, Jx)

        rot_yy = ps.Operator(N)
        rot_yy += "Y", j, "Y", j%N+1
        push!(gate_list, rot_yy)
        push!(angle_list, Jx)

        rot_zz = ps.Operator(N)
        rot_zz += "Z", j, "Z", j%N+1
        push!(gate_list, rot_zz)
        push!(angle_list, Jz)

        rot_3 = ps.Operator(N)
        rot_3 += "Z", j
        push!(gate_list, rot_3)
        push!(angle_list, θ3)

        rot_4 = ps.Operator(N)
        rot_4 += "Z", j%N+1
        push!(gate_list, rot_4)
        push!(angle_list, θ4)
    end
    return gate_list, angle_list
end

"""
    manual_circuit(N)

Construct a U(1) circuit with manually specified parameters.

Similar to random_circuit but uses fixed parameters from params.json instead of
random angles. Useful for studying specific parameter regimes.

# Arguments
- `N`: Number of qubits

# Returns
- `gate_list`: List of Pauli generators
- `angle_list`: Corresponding angles
"""
function manual_circuit(N)
    angles = load_manual(N)
    gate_list = []
    angle_list = []

    for j in 1:2:N
        θ1, θ2, Jx, Jz, θ3, θ4 = angles["θ1"], angles["θ2"], angles["Jx"], angles["Jz"], angles["θ3"], angles["θ4"]

        rot_1 = ps.Operator(N)
        rot_1 += "Z", j
        push!(gate_list, rot_1)
        push!(angle_list, θ1)

        rot_2 = ps.Operator(N)
        rot_2 += "Z", j+1
        push!(gate_list, rot_2)
        push!(angle_list, θ2)

        rot_xx = ps.Operator(N)
        rot_xx += "X", j, "X", j+1
        push!(gate_list, rot_xx)
        push!(angle_list, Jx)

        rot_yy = ps.Operator(N)
        rot_yy += "Y", j, "Y", j+1
        push!(gate_list, rot_yy)
        push!(angle_list, Jx)

        rot_zz = ps.Operator(N)
        rot_zz += "Z", j, "Z", j+1
        push!(gate_list, rot_zz)
        push!(angle_list, Jz)

        rot_3 = ps.Operator(N)
        rot_3 += "Z", j
        push!(gate_list, rot_3)
        push!(angle_list, θ3)

        rot_4 = ps.Operator(N)
        rot_4 += "Z", j+1
        push!(gate_list, rot_4)
        push!(angle_list, θ4)
    end

    for j in 2:2:N
        θ1, θ2, Jx, Jz, θ3, θ4 = angles["θ1"], angles["θ2"], angles["Jx"], angles["Jz"], angles["θ3"], angles["θ4"]

        rot_1 = ps.Operator(N)
        rot_1 += "Z", j
        push!(gate_list, rot_1)
        push!(angle_list, θ1)

        rot_2 = ps.Operator(N)
        rot_2 += "Z", j%N+1
        push!(gate_list, rot_2)
        push!(angle_list, θ2)

        rot_xx = ps.Operator(N)
        rot_xx += "X", j, "X", j%N+1
        push!(gate_list, rot_xx)
        push!(angle_list, Jx)

        rot_yy = ps.Operator(N)
        rot_yy += "Y", j, "Y", j%N+1
        push!(gate_list, rot_yy)
        push!(angle_list, Jx)

        rot_zz = ps.Operator(N)
        rot_zz += "Z", j, "Z", j%N+1
        push!(gate_list, rot_zz)
        push!(angle_list, Jz)

        rot_3 = ps.Operator(N)
        rot_3 += "Z", j
        push!(gate_list, rot_3)
        push!(angle_list, θ3)

        rot_4 = ps.Operator(N)
        rot_4 += "Z", j%N+1
        push!(gate_list, rot_4)
        push!(angle_list, θ4)
    end
    return gate_list, angle_list
end



### Evolution ###

"""
    load_angles(N::Int)

Load pre-generated random angles for N-qubit circuits.

Reads random angle parameters from random_archive/angles_N{N}.json.
These angles define the random U(1) circuits for different trials.

# Arguments
- `N`: Number of qubits

# Returns
- Array of angle dictionaries for multiple trials
"""
function load_angles(N::Int)
    filename = "random_archive/angles_N$(N).json"
    if !isfile(filename)
        error("File $filename does not exist.")
    end
    return JSON.parsefile(filename)
end

"""
    load_manual(N::Int)

Load manual circuit parameters from params.json.

# Arguments
- `N`: Number of qubits (must match value in params.json)

# Returns
- Dictionary of circuit parameters
"""
function load_manual(N::Int)
    filename = "params.json"
    if !isfile(filename)
        error("File $filename does not exist.")
    end
    data = JSON.parsefile(filename)
    if data["N"] != N
        error("Incorrect N value")
    else
        return data
    end
end

"""
    weight_dist(O)

Compute the weight distribution of a Pauli operator.

The weight of a Pauli string is the number of non-identity Pauli matrices.
This function computes how much amplitude (coefficient magnitude) is concentrated
at each weight level, providing insight into operator spreading.

# Arguments
- `O`: Pauli operator

# Returns
- Dictionary mapping weight → total amplitude at that weight
"""
function weight_dist(O)
    dist = Dict{typeof(ps.pauli_weight(O.strings[1])), typeof(O.coeffs[1])}()
    for I in eachindex(O.strings)
        key = ps.pauli_weight(O.strings[I])
        val = abs(O.coeffs[I])
        dist[key] = get(dist, key, zero(val)) + val
    end
    return dist
end

"""
    two_point_correlators_random(N, num_steps, trial, O; M=2^10, noise=0, keep=Operator(0), calc_weight_dist=true, save_coeffs=true)

Compute time evolution of correlation functions using random U(1) circuits.

This is the main simulation function. It evolves a Pauli operator through a random
U(1) circuit and computes correlation functions ⟨Z_i(t)⟩ = Tr[O(t) Z_i] / 2^N at each time step.

The Pauli propagation method allows efficient computation without storing the full
quantum state, making it feasible to study large systems.

# Arguments
- `N`: Number of qubits
- `num_steps`: Number of time steps to evolve
- `trial`: Which random circuit realization to use
- `O`: Initial Pauli operator (typically Z_site for some site)
- `M`: Truncation parameter for Pauli operator size
- `noise`: Noise level
- `keep`: Operators to preserve during truncation
- `calc_weight_dist`: Whether to track weight distribution evolution
- `save_coeffs`: Whether to save full operator coefficients

# Returns
- `correlators`: Time series of correlation functions ⟨Z_i(t)⟩
- `angle_list`: Circuit angles used
- `weight_dist_array`: Weight distributions at each time step
- `coeffs`: Full operator coefficients (if saved)
"""
function two_point_correlators_random(N, num_steps, trial, O; M=2^10, noise=0, keep=Operator(0), calc_weight_dist=true, save_coeffs=true)
    correlators = []
    weight_dist_array = []
    coeffs = []
    gate_list, angle_list = random_circuit(N, trial)
    all_local_Z = single_Z_operators(N)
    for t in 1:num_steps
        println("Time Step $t")
        correlators_t = [ps.trace_product(O, local_Z)/big(2)^N for local_Z in all_local_Z]
        push!(correlators, correlators_t)

        if calc_weight_dist
            push!(weight_dist_array, weight_dist(O))
        end

        if save_coeffs
            push!(coeffs, ps.op_to_strings(O))
        end

        O = apply_gate_list(O, gate_list, angle_list; M=M, noise=noise, keep=keep)
    end

    output = [real.(correlators), angle_list, weight_dist_array, coeffs]

    return output
end;

"""
    two_point_correlators_manual(N, num_steps, O; M=2^10, noise=0, keep=Operator(0), calc_weight_dist=true, save_coeffs=true)

Compute correlation functions using manual (fixed) circuit parameters.

Similar to two_point_correlators_random but uses fixed parameters instead of random ones.

# Arguments
- Same as two_point_correlators_random except no `trial` parameter

# Returns
- Same as two_point_correlators_random
"""
function two_point_correlators_manual(N, num_steps, O; M=2^10, noise=0, keep=Operator(0), calc_weight_dist=true, save_coeffs=true)
    correlators = []
    weight_dist_array = []
    coeffs = []
    gate_list, angle_list = manual_circuit(N)
    all_local_Z = single_Z_operators(N)
    for t in 1:num_steps
        println("Time Step $t")
        correlators_t = [ps.trace_product(O, local_Z)/big(2)^N for local_Z in all_local_Z]
        push!(correlators, correlators_t)

        if calc_weight_dist
            push!(weight_dist_array, weight_dist(O))
        end

        if save_coeffs
            push!(coeffs, ps.op_to_strings(O))
        end

        O = apply_gate_list(O, gate_list, angle_list; M=M, noise=noise, keep=keep)
    end

    output = [real.(correlators), angle_list, weight_dist_array, coeffs]

    return output
end;


"""
    run_pauli_trial(N, num_steps, M, site, trial; save_dir="pauli_results", calc_weight_dist=true, save_coeffs=true)

Run a complete Pauli propagation simulation for a single trial.

This function sets up and runs a full simulation:
1. Creates initial operator Z_site
2. Defines operators to keep during truncation (all local Z operators)
3. Runs the time evolution
4. Saves results with metadata

The goal is to study how local magnetization Z_site spreads and correlates with
other sites under U(1) circuit dynamics.

# Arguments
- `N`: Number of qubits
- `num_steps`: Time steps to evolve
- `M`: Maximum Pauli terms to keep
- `site`: Initial site for Z operator
- `trial`: Random circuit realization
- `save_dir`: Directory to save results
- `calc_weight_dist`: Track weight distribution
- `save_coeffs`: Save full coefficients

# Returns
- Runtime of the simulation
"""
function run_pauli_trial(N, num_steps, M, site, trial; save_dir="pauli_results", calc_weight_dist=true, save_coeffs=true)
    mkpath(save_dir)

    keep_op = ps.Operator(N)
    for local_Z in single_Z_operators(N)
        keep_op += local_Z
    end

    O = ps.Operator(N)
    O += "Z", site

    println("Running PauliStrings: N=$N, M=$M, site=$site, trial=$trial")

    to = TimerOutput()
    runtime = @elapsed begin
        @timeit to "Pauli evolution" begin
            ret = two_point_correlators_random(N, num_steps, trial, O; M=M, noise=0, keep=keep_op, calc_weight_dist=calc_weight_dist, save_coeffs=save_coeffs)
            results, angle_list, weight_dist_array, coeffs = ret
        end
    end

    # Construct metadata dictionary
    params = Dict(
        "N" => N,
        "num_steps" => num_steps,
        "M" => M,
        "site" => site,
        "trial" => trial,
        "runtime" => runtime,
        "timestamp" => Dates.now(),
        "save_dir" => save_dir,
        "angle_list" => angle_list,
        "weight_dist_array_fix" => weight_dist_array,
        "coeffs" => coeffs
    )

    filepath = joinpath(save_dir, "pauli_M$(M)_site$(site)_trial$(trial)_N$(N).jld2")
    @save filepath results params

    return runtime
end


"""
    run_pauli_manual(N, num_steps, M, site; save_dir="pauli_results_manual", calc_weight_dist=true, save_coeffs=true)

Run simulation with manual (fixed) circuit parameters.

Similar to run_pauli_trial but uses fixed parameters instead of random ones.
Useful for studying specific parameter regimes or debugging.

# Arguments
- Same as run_pauli_trial except no `trial` parameter

# Returns
- Runtime of the simulation
"""
function run_pauli_manual(N, num_steps, M, site; save_dir="pauli_results_manual", calc_weight_dist=true, save_coeffs=true)
    mkpath(save_dir)

    keep_op = ps.Operator(N)
    for local_Z in single_Z_operators(N)
        keep_op += local_Z
    end

    O = ps.Operator(N)
    O += "Z", site

    println("Running PauliStrings: N=$N, M=$M, site=$site")

    to = TimerOutput()
    runtime = @elapsed begin
        @timeit to "Pauli evolution" begin
            ret = two_point_correlators_manual(N, num_steps, O; M=M, noise=0, keep=keep_op, calc_weight_dist=calc_weight_dist, save_coeffs=save_coeffs)
            results, angle_list, weight_dist_array, coeffs = ret
        end
    end

    # Construct metadata dictionary
    params = Dict(
        "N" => N,
        "num_steps" => num_steps,
        "M" => M,
        "site" => site,
        "runtime" => runtime,
        "timestamp" => Dates.now(),
        "save_dir" => save_dir,
        "angle_list" => angle_list,
        "weight_dist_array_fix" => weight_dist_array,
        "coeffs" => coeffs
    )

    filepath = joinpath(save_dir, "pauli_M$(M)_site$(site)_N$(N).jld2")
    @save filepath results params

    return runtime
end